<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TalosDesk.App\TalosDesk.App.csproj" />
    <ProjectReference Include="..\..\src\TalosDesk.Core\TalosDesk.Core.csproj" />
  </ItemGroup>
</Project>
