<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TalosDesk.Core\TalosDesk.Core.csproj" />
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <Resource Include="Assets\TalosDeskMark.png" />
    <Resource Include="Assets\TalosDeskMark.ico" />
    <Resource Include="Editing\PowerShellHighlighting.xshd" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\TalosDeskMark.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
